### ISSUE TITLE
Server/Client not compatible with WINE

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#375]
_From [AHeinerm](https://code.google.com/u/AHeinerm/) on April 13, 2011 16:02:23_

On a linux platform using Wine, the BWAPI launcher works correctly, but BWAPI itself causes a problem with the following error:

~~~
Starcraft was unable to open a required file. This indicates that the installation of Starcraft has been corrupted. Please uninstall and then reinstall Starcraft using the program "SETUP.EXE" on the Starcraft CD-ROM.

The problem occurred while trying to load the file:
  font\font.gid
  File not found
~~~

This also happens to be the very first file loaded from an MPQ in the entire application.

More investigation is necessary to identify the cause.

_Original issue: http://code.google.com/p/bwapi/issues/detail?id=377_

**Comment by joankaradimov** [comment]
I had a similar problem with a little thing I am doing. Some research on the inner workings of storm.dll led me to [StormLib's site](http://www.zezula.net/en/mpq/stormdll.html). There is something interesting there:

> Storm.dll can be used only when it is linked statically, using import library. If it is loaded using LoadLibrary, the library will corrupt internal decrypt buffer and functions for file reading will not work anymore

When this protection against `LoadLibrary` kicks in all file reading calls in storm.dll start failing. The error displays `font/font.gid` simply because this is the first file being read from the MPQs.

To work around the problem I came up with a little piece of code. It needs to be called as early as possible -- before `Starcraft.exe` starts calling stuff from `storm.dll`:
```c
	HINSTANCE storm_dll = LoadLibrary(L"storm.dll");
	void** storm_1505E5E4 = (void**)((char*)storm_dll + 0x5E5E4);
	*storm_1505E5E4 = 0;
```

This basically deinitializes some memory that is intentionally initialized with a wrong seed (or at least I assume it is a seed of some sort). It does cause a one time memory leak of 5120 bytes. But I am sure we can all live with that (there is a way to solve it, but meh).

I can provide you with more details of the inner workings of the protection if you are interested.

**Comment by heinermann** [comment]
BWAPI is using storm statically, so I don't think that is the problem.

**Comment by heinermann** [comment]
Hey @joankaradimov , thanks to your suggestion I've fixed the loading issue. This issue will remain open for tracking the `PIPE_NOWAIT` issue in Wine, but the loading issue (#598) is now fixed. To avoid the hack you provided, I simply call SFileDestroy() (a Storm export), which fixes the issue (SFileInit() is called again when any file is loaded by Storm).

**Comment by heinermann** [comment]
Closing this issue since it was reused for different things multiple times.
