### ISSUE TITLE
A unit is reported as both isMoving() == true and isIdle() == true

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#527]
For example, an SCV has the BWAPI order Guard and is reported as both idle and moving at the same time. I've encountered it happening with Terran Marines (BWAPI order "PlayerGuard" in this case), too.

**Comment by heinermann** [comment]
That's because it's both moving and idle. (i.e. you tell an SCV to move and then tell it to stop, it becomes idle while it's still moving, slowing to a halt to stop moving)

Larvae are prime examples of both moving and idle. It seems any unit does the same when stopping, there will be a couple of frames where they're still moving but considered idle.

I right clicked a structure with a science vessel and when it reached the structure, it spent a significant amount of frames from some range of the structure to the center of it complaining about being idle and moving at the same time, but it did reach the structure before "becoming idle". I suppose if you wanted to move it to the structure's center you would have it right click the ground.

But I don't think it's really a bug. I think the current behaviour is fine. Idle just tells me when my unit is in an idle state. If `isIdle()` is changed then I'd rather have another function behave exactly like the current `isIdle()`. `isMoving()` seems to be working fine. In fact you would lose frames waiting for a unit to stop moving.
