### ISSUE TITLE
Allow builds when git.exe is not found

### ISSUE THREAD

**Issue by ghost** [bwapi/bwapi#544]
Generated svnrev.h doesn't compile when git.exe is not found.

-- Please don't erase issues. - Heinermann

**Comment by heinermann** [comment]
Would have to check if `git.exe` exists.

This is used to identify which revision of BWAPI was compiled. It should be changed to the current commit hash instead because revisions were back when we were still using svn, and the current revision thing is just an approximation of where we left off plus the number of git commits.

So the solution would actually be to replace the revision(integer) system with the hash(string) system and  use a default string of "No hash available" if `git.exe` wasn't found or encountered some error.

**Comment by GeEom** [comment]
Pseudo deletion like this is pretty annoying Rat.

**Comment by krasi0** [comment]
Agreed
