### ISSUE TITLE
Deceiving function overloads

### ISSUE THREAD

**Issue by Predelnik** [bwapi/bwapi#568]
Noticed interesting thing: There's a couple of functions i.e. `canAttack` which have two overloads - one takes `bool` only (`checkCommandibility`), the other takes `UnitOrPosition` argument, and then a couple of defaultable arguments. 

So the problem is that when you call them with single argument of type `Unit`, you are naturally expecting that `UnitOrPosition` version with the rest arguments equal to default will be called. What actually will be called is ...`bool` version. Luckily it is indicated when you compile with `\W4` which BWAPI is compiled with but since BWAPI seemingly doesn't have such calls internally it compiles fine. Users compiling with lower level of warnings may be silently harmed.

The rest of functions like that i.e. receiving `Unit` itself, `UnitType`, `Position` are probably fine but ones with `UnitOrPosition` are really sneaky :)

**Comment by krasi0** [comment]
Hmm. Sounds like a place where the design of the class might use an
additional touch

**Comment by heinermann** [comment]
I actually don't like how this was done. There are nearly 100 virtual functions for these, which can most if not all be non-virtual. In fact I question whether it should even be in the UnitInterface class. The majority of this logic (which has some duplication) takes about 3000 lines of code in Templates.h and I'm sure is more code than Broodwar has itself.

Since it's an interface change it will have to be put in 4.2.0. If you have any suggestions for changing the design let me know.

**Comment by heinermann** [comment]
Removed PositionOrUnit in d72960e9. Is there a piece of code you have that raises this warning so that I can test if it's still an issue?

**Comment by heinermann** [comment]
Going to mark as resolved since `PositionOrUnit` (which is what caused the issue) was removed. Please re-open if it is still an issue.
