### ISSUE TITLE
Can't determine requirements for tech types generically

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#588]
It's currently not possible for [TechType](http://bwapi.github.io/class_b_w_a_p_i_1_1_tech_type.html) to determine any required [unit types](http://bwapi.github.io/class_b_w_a_p_i_1_1_unit_type.html) that the technology may require. An example (possibly the only case) is with [Lurker Aspect](http://bwapi.github.io/namespace_b_w_a_p_i_1_1_tech_types.html#a98032f71ac0e415a4cee1544f4f7ed5c).

**Comment by BoomerangAide** [comment]
Isn't the issue that this requirement (required unit type) is tied to an unit, not to the technology?
The best example is Siege Mode, where the hero unit and the normal unit use the same technology, but with different requirement and effect defined on the corresponding button of the unit.

**Comment by heinermann** [comment]
The issue isn't for using the tech, it's for researching it. For example to research lurker aspect, I need a lair. But there's no way in code to identify that I first need to build the lair before researching lurker aspect.

**Comment by BoomerangAide** [comment]
I see.
Indeed there's no "generic" way to do it.Function "0046D610  parseRequirementOpcodes" need an actual unit, not just an unitId, to do the check, so I guess the solution is to hardcode it.
The modding tool Firegraft can help since it convert the opcodes in text (in Dat Requirements / Research Tech)
