### ISSUE TITLE
Getting screenshot at each frame

### ISSUE THREAD

**Issue by edran** [bwapi/bwapi#596]
Apparently the ability to record screen dumps was added in #178 but was later removed. 

I've tried using the Windows input API to simulate a `CTRL+PtrScreen` keypress in onFrame(), but the game becomes extremely slow and jerky, plus a "Screen Captured to File ..." string is printed on screen, which means that sequential screenshots will also contain those strings.

Is there a better way to get a dump of the screen with and without the GUI in some particular format (say, bitmap)?

**Comment by heinermann** [comment]
I removed the video recording, which used windows video recording API, because it was simply too slow. Naturally it could be faster in another thread, but there's no reason for me to waste my time maintaining something that can already be done using another tool. So I suggest an external screen capture tool that records the gameplay.

As for recording without the UI, there's some graphics engine work in the SDL-Experiment branch, but it's not ready.

**Comment by edran** [comment]
I see, that makes sense.
I'll give a few screen records a try and see how it goes :)

**Comment by heinermann** [comment]
Since external tools already exist for screen recording and streaming, there is no need to implement this functionality in BWAPI.
