### ISSUE TITLE
Unable to refer to BW/Console output streams.

### ISSUE THREAD

**Issue by heinermann** [bwapi/bwapi#640]
This was added by #635.

When trying to use this in an AI module, the following compiler error occurs:

~~~
Error	47	error LNK1120: 1 unresolved externals	C:\Users\Adam\bwapi4\bwapi\Release\DevAIModule.dll	1	1	DevAIModule
Error	46	error LNK2001: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & BWAPI::bwout" (?bwout@BWAPI@@3AAV?$basic_ostream@DU?$char_traits@D@std@@@std@@A)	C:\Users\Adam\bwapi4\bwapi\DevAIModule\DevAIModule.obj	DevAIModule
~~~

This is the result of Streams.cpp being part of BWAPI (instead of BWAPILib) and it happens to be tightly coupled (and bound to BW).

**Comment by heinermann** [comment]
@blole

**Comment by heinermann** [comment]
There is an exception when exiting the game in DEBUG mode in boost::iostreams.

**Comment by blole** [comment]
To the first issue, I think of 3 classes of solutions

## Make the streams fields in BWAPI::Game
This would mean that you have to write
```Broodwar->bwout << ...``` instead of
```BWAPI::bwout << ...``` or just
```bwout << ...``` if you're already in/using the BWAPI namespace.

## Separate instantiation of the streams for the AI module

* add a Game.getFont()
* move Font.h to include/
* move Font.cpp to BWAPILIB
* move Streams.cpp to BWAPILIB

## Import the streams
Pass pointers to the streams on to the AI module in some way.
E.g. like the BroodwarPtr is passed now through a exported function:
 ```c++
namespace BWAPI
{
  std::ostream& bwout
}
extern "C" __declspec(dllexport) void setBwout(std::ostream* bwout) { BWAPI::bwout = bwout; }
```

Or by exporting the streams and letting bwapi.dll set them when it injects the module:
```c++
namespace BWAPI
{
  extern "C" __declspec(dllexport) std::ostream* bwout;
}
```

Or by importing the streams from bwapi.dll automatically, though this would make AI modules dependent on dynamically linking with bwapi.dll on runtime, which shouldn't be a problem since they're already very dependent on bwapi.dll.
```c++
namespace BWAPI
{
  extern "C" __declspec(dllimport) std::ostream& bwout;
}
```
----

I think this last solution sounds best, unless the runtime dependency on bwapi.dll has been deliberately avoided because it causes problems when bridging bwapi from other languages or cross version compatability or something.

----

Note that std::cout etc. are already shared since they're defined like
```c++
namespace std
{
  extern __declspec(dllimport) ostream cout;
}
```

**Comment by heinermann** [comment]
BWAPI has a client/server bridge that you can't just pass symbols through. It passes all the game data via shared memory and sends commands back to BWAPI using pipes. It's actually a terrible system, but that's what's there right now.

So using DLL imports won't work.

The easiest solution would be to just get the width of all the characters from the default font and store them in some array instead of exposing BW Font data. This is also a terrible solution, but is good enough until it's replaced by some Font APIs in Broodwar.

Then we could either
A. Have some `getCharacterWidth`, `getTextHeight`, etc. APIs in Broodwar. We would be copying fixed size arrays into shared memory. This would have limited access to font data though, but it should provide everything your need for this in particular.
B. Have a `getFont` API that just returns a BW Font object (your suggestion). I'm not sure how we would copy the font object itself into shared memory though (should we allocate a new block for each one or use our current block?) I'm convinced this would require more effort though.
