### ISSUE TITLE
Hooking GetProcAddress()

### ISSUE THREAD

**Issue by xboi209** [bwapi/bwapi#650]
I've stripped the HackUtil functions into my own non-bwapi related project and attempted to hook ````GetProcAddress()```` exactly how I see the other WinAPI functions being hooked in BWAPI, but could only capture one call to ````GetProcAddress()````(none if BW is in windowed mode). I've also hooked ````GetFileTimeAsSystemTime()```` to show that the code is written properly, so I feel that something is wrong somehow.
https://gist.github.com/xboi209/16670bcc81226c1887ce

**Comment by heinermann** [comment]
This sounds correct. BW doesn't call GetProcAddress for anything outside the standard library. I also don't recall GetFileTimeAsSystemTime being called in BW. What's the problem?

**Comment by xboi209** [comment]
````battle.snp```` definitely calls ````GetProcAddress()```` for a few things, one of them being the ````CheckRevision()```` function located in ````ver-ix86-1.dll````. I'm unable to capture any of these calls however.
GetFileTimeAsSystemTime() is called by ````CheckRevision()````.

**Comment by heinermann** [comment]
That's battle.SNP, not StarCraft.exe. It's a different module, so you need to make a different hook for it. Closing since it's not a BWAPI issue.

Also I wouldn't recommend using BWAPI's HackUtil, as it is quite old and sloppy. Do you know if there is a hooking library available? I would definitely consider switching to it instead.
