### ISSUE TITLE
Error C2280

### ISSUE THREAD

**Issue by Cheong-mok** [bwapi/bwapi#677]
I've worked with my team mate.

I use Windows 10 x64 machine with VS2015, VS2013, and other mates use Windows 7 x64 machine with VS2013.

On Windows 7 machine, there's no matter to build our code, however, on my Windows 10 machine, there are some problems to build with Error: C2280, likes,
`1>TacticsOrder.cpp(53): error C2280: 'BWAPI::Unitset &BWAPI::Unitset::operator =(const BWAPI::Unitset```
&)' : attempting to reference a deleted function
1>          C:\Program Files (x86)\BWAPI\include\BWAPI/Unitset.h(184) : compiler has generated 'BWAPI::Unitset::operator =' here`

Could you help me to solve this problem?

**Comment by heinermann** [comment]
Will check it out within the next 8-14 hours.

**Comment by heinermann** [comment]
It appears to work find for me.

**Comment by michelbieleveld** [comment]
I have the same problem it seems to be related to VS2015 and that the operator= is now deleted in another case, a recent change for the new compiler if I understood correctly. A possible fix is listed below but at the moment no way of testing the consequences ( just starting out and no compiling bot yet). 

Just as a side note, while BWAPI now compiles with VS2015 and generates the library the problem seems to be compiling BWTA2 as it has many dependencies all with their dependencies etc.  It might be easiest to stick with VS2013.

diff --git a/bwapi/BWAPILIB/Source/Unitset.cpp b/bwapi/BWAPILIB/Source/Unitset.cpp
index cca993c..8f5a755 100644
--- a/bwapi/BWAPILIB/Source/Unitset.cpp
+++ b/bwapi/BWAPILIB/Source/Unitset.cpp
@@ -1,3 +1,5 @@
+#include "..\..\include\BWAPI\Unitset.h"^M
+#include "..\..\include\BWAPI\Unitset.h"^M
 #include <BWAPI/Unitset.h>
 #include <BWAPI/UnitCommand.h>
 #include <BWAPI/Position.h>
@@ -12,6 +14,17 @@ namespace BWAPI
   // initialize no-set
   const Unitset Unitset::none;

+  Unitset & Unitset::operator=(const Unitset & that)^M
+  {^M
+         this->clear();^M
+         for (auto &u : that)^M
+         {^M
+                 auto units = u->getLoadedUnits();^M
+                 this->insert(units.begin(), units.end());^M
+         }^M
+         return *this;^M
+  }^M
+^M
   ////////////////////////////////////////////////////////// Position
   Position Unitset::getPosition() const
   {


and


:\Documents\Visual Studio 2015\Projects\bwapi>git diff HEAD^^ HEAD bwapi/include/BWAPI/Unitset.h
diff --git a/bwapi/include/BWAPI/Unitset.h b/bwapi/include/BWAPI/Unitset.h
index d4def24..226e105 100644
--- a/bwapi/include/BWAPI/Unitset.h
+++ b/bwapi/include/BWAPI/Unitset.h
@@ -22,6 +22,10 @@ namespace BWAPI
     /// <summary>A blank Unitset containing no elements.</summary> This is typically used as a
     /// return value for BWAPI interface functions that have encountered an error.
     static const Unitset none;
+       Unitset(const Unitset&) = default;^M
+       //Unitset& operator=(Unitset&&);^M
+       Unitset& operator=(const Unitset& that);^M
+       Unitset() {}^M


     /// <summary>Calculates the average of all valid Unit positions in this set.</summary>

**Comment by albertouri** [comment]
Side note following: I have been working on a big BWTA2 update that requires less dependencies (and less analysis time), but I don't have an estimated release date (I will try my best to release it once the new BWAPI version is official)

**Comment by michelbieleveld** [comment]
Great work, and looking forward to the new version. Will it be compatible with vs2015?

**Comment by albertouri** [comment]
Yes, it will be :simple_smile:

**Comment by heinermann** [comment]
We're using VS2017 now in 2019, so I'm assuming this is no longer an issue? Please re-open if it is.
