### ISSUE TITLE
Incorrect VC++ Redist shipped with BWAPI 4.2.0

### ISSUE THREAD

**Issue by adakitesystems** [bwapi/bwapi#724]
Both the manual `BWAPI_420.7z` and auto `BWAPI_420_Setup.exe` install packages are shipped with `VC++ Redist 2013` where `VC++ Redist 2015` is required.

**Comment by edran** [comment]
VC++ Redist 2015 can be downloaded here: https://www.microsoft.com/en-us/download/details.aspx?id=48145 - Choose the x86 version.

**Comment by chriscoxe** [comment]
BWAPI 4.2.0 is built using Visual Studio 2017, not 2015, so I think the VC++ Redist 2017 should be used, not 2015. I only needed to install the 2017 redist to make Chaoslauncher inject successfully on a vanilla Windows 7 SP1 VirtualBox VM.

**Comment by chriscoxe** [comment]
Note that if you are using a 64-bit OS, the 2017 redist should be the x86 variant. The x64 variant can also be installed at the same time but the x86 variant is the one that is needed by BWAPI (the x64 variant is not needed by BWAPI). At the time of writing (11 Aug 2017), the latest x86 redist for 2017 is shown in Add/Remove Programs as "Microsoft Visual C++ 2017 Redistributable (x86) - 14.10.25017".

Also note that if the 2015 x86 redist is already installed when you install the 2017 x86 redist, it replaces the 2015 x86 redist and the 2015 one is no longer shown in the list of installed software - the 2017 x86 redist is shown instead.

**Comment by adakitesystems** [comment]
I receive the following error when trying to use a 4.2.0 BWAPI.dll on a fresh Win7 SP1 32-bit install: "The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem." After installing VC++ Redist 2015, I no longer receive this message. I see now in the project solution files of BWAPI that the toolset is set to 141. In this case, I agree VC++ Redist 2017 should be used even though VC++ Redist 2015 seems to resolve the issue.

**Comment by chriscoxe** [comment]
I've updated the redist to the latest version, in the "develop" branch.  4.2.0 has already been released, so it will be in the next release that is a higher version number than that.  Microsoft seem to update VS2017 & the redist quite often these days, so as part of every release,  I suggest checking whether the compiler version on AppVeyor has changed since the last release, and if so, update to the latest (x86) "Microsoft Visual C++ Redistributable for Visual Studio 2017" redist from https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads.  This will ensure that future releases (and bots built using it) will work on machines that don't have VS2017 installed.  Otherwise theoretically, BWAI/bots might experience some strange behaviour due to compatibility problems.
