### ISSUE TITLE
Cannot build the ExampleAIModule project in RELEASE mode

### ISSUE THREAD

**Issue by eralogos** [bwapi/bwapi#737]
Environment: 
Windows 10
BWAPI 4.2.0    install path E:\BWAPI
StarCraft 1.16.1     install path: E:\starcraft1\Starcraft
Visual Studio 2013 ultimate    install path: E:\visualstudio2013
Visual Studio platform toolset: Visual Studio 2013 (v120)
These errors are not hightlighted in the compiler and if I double click to locate an error, prompt says "this document is opened by another project“

My computer installed Starcraft remastered and StarcraftII simultaneously. 

Some of the errors are listed bellow and the total number is 308

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2146	syntax error : missing ';' before identifier 'Type' (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C2071	'BWAPI::Type<T,UnknownId>::constexpr' : illegal storage class (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C2143	syntax error : missing ';' before 'user-defined conversion' (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	77	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	77	
Error	C2144	syntax error : 'int' should be preceded by ';' (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	82	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	82	
Error	C2144	syntax error : 'bool' should be preceded by ';' (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	90	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	90	
Error	C2071	'BWAPI::Type<BWAPI::UnitType,233>::constexpr' : illegal storage class (Source\ExampleAIModule.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C2146	syntax error : missing ';' before identifier 'Type' (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C2071	'BWAPI::Type<T,UnknownId>::constexpr' : illegal storage class (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	66	
Error	C2143	syntax error : missing ';' before 'user-defined conversion' (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	77	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	77	
Error	C2144	syntax error : 'int' should be preceded by ';' (Source\Dll.cpp)	ExampleAIModule	E:\BWAPI\include\BWAPI\Type.h	82	
...

**Comment by heinermann** [comment]
You cannot use Visual Studio 2013 to build 4.2.0 bots. Try using VS 2017.

**Comment by eralogos** [comment]
I got this error after using Visual Studio 2017 and Visual Studio 2017 (v141) toolset.(windows SDK version 10.0.10586.0) 
Error	C1047	The object or library file '../lib/BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries	ExampleAIModule	E:\BWAPI\ExampleAIModule\LINK	1	

So I tried to rebuild the BWAPI.lib. I rebuilt the BWAPILIB project and got this error: 
Error	C1083	Cannot open include file: '../../svnrev.h': No such file or directory	BWAPILIB	E:\bwapi-master\bwapi\BWAPILIB\Source\BWAPI.cpp	2	

Noticing the path, I changed to use BWAPILIB project in the bwapi-master folder, otherwise I got errors like this one:
Error	C1083	Cannot open include file: '../../Debug.h': No such file or directory	BWAPILIB	E:\BWAPI\BWAPILIB\Source\Color.cpp	4	

I noticed there is a Visual Studio project called SVNRevGen, so I tried to build it. Then it got these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "pushd "E:\bwapi-master\bwapi\SVNRevGen\"
cscript "./revisionUpdate.vbs"
popd
:VCEnd" exited with code 1.	SVNRevGen	E:\Visual Studio\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	203	
Error		Can not find script file "E:\bwapi-master\bwapi\SVNRevGen\revisionUpdate.vbs".	SVNRevGen	E:\bwapi-master\bwapi\SVNRevGen\EXEC	1

If I directly ran revisionUpdate.vbs, it got an prompt with error "Type mismatch: 'Clnt'"  in line 11 char 3

**Comment by benjamin-ross** [comment]
I also cannot build the project in release mode using VS 2017. Any update on that issue ?

**Comment by heinermann** [comment]
It might be because of a VS update. Will look into it.

**Comment by adakitesystems** [comment]
Prior to installing Visual Studio 2017 update 15.3.5, I did not have any issues. After installing the update, I received the error "**LINK : fatal error C1047: The object or library file 'BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries**". Reinstalling VS did not resolve the issue as it appears all fresh installs are updated directly to 15.3.5.

I am, however, able to compile BWAPI 4.2.0 in Release Mode Win32 and rename BWAPILIB.lib to BWAPI.lib to be used in my previous projects. The ExampleAIModule is also working for me. I am using Windows 7 32-bit. The source files I used are from: https://github.com/bwapi/bwapi/archive/v4.2.0.tar.gz

**Comment by BryanSWeber** [comment]
Possibly unrelated, but I am having the same error message.

I am trying to recompile the BWAPI 4.1.2 using VS 2013.
I am using Windows 10 64 bit.   I have tried uninstalling BWAPI 4.1.2 and reinstalling it from github.

**Comment by halfhorst** [comment]
I'm getting the same issue as @adakitesystems:

in Visual Studio 2017 ver 15.4.4 trying to build the example AI module in release mode from BWAPI 4.2.0 results in the same linker error. Gave a little go building BWAPILIB but quit because a bunch of files #include "../../Debug.h" but that header appears to be only one directory up, not two. 

But, I can add a bit of info: the build of the example AI module succeeds in debug mode.

**Comment by elibc** [comment]
I've managed to work around this problem by cloning the whole BWAPI repository in a separate folder, building the solution, and then copying the output files from the lib folder to the lib folder used for building the ExampleAIModule. 
Afterwards I've managed to successfully build the solution in Release configuration and run the AI.

**Comment by heinermann** [comment]
Does using [the latest build artifact](https://ci.appveyor.com/project/heinermann/bwapi/build/4.2.0.90/artifacts) work?

**Comment by nyeecola** [comment]
Yes, it does.

**Comment by ankmairdor** [comment]
I recently had troubles building BWAPI 4.2.0 from source. I first downloaded the source into a normal directory instead of cloning it with git. I encountered the same error "Type mismatch: 'Clnt'" as @eralogos when building and when running "revisionUpdate.vbs". During the build this led to a cascade of errors, so the build was mostly a failure.
I tracked the source of my problem to the message "fatal: Not a git repository (or any of the parent directories): .git", which is issued because my downloads were not in repositories. Since I have git "revisionUpdate.vbs" tries to ask git for the number of revisions since the head, but 'CInt' throws an error if there is no numeric value. I replaced
`revNumber = 2383 + CInt(gitResult.StdOut.ReadAll())` 
with
```
  data = gitResult.StdOut.ReadAll()
  If IsNumeric(data) Then
    revNumber = 2383 + CInt(data)
  Else
    revNumber = -1
  End If
```
and it seems to work for downloaded and cloned. Both compiled without a problem. I'm not too familiar with any of this, so I can't guarantee no new problems.

**Comment by chriscoxe** [comment]
I have solved it without needing to rebuild BWAPI 4.2.0.

Short story: if you have version 15.3 or higher of Visual Studio Community 2017 currently installed but you still want your bot to work with the currently supported versions of BWAPI.dll & TournamentModule.dll on SSCAIT and tools like the current/recent versions of https://github.com/davechurchill/StarcraftAITournamentManager (e.g. for CIG 2018 or maybe AIIDE 2018) or BWAPI_420.old.7z or BWAPI_420_Setup.old.exe (rather than BWAPI.VS.15.7.3.7z or BWAPI_Setup.VS.15.7.3.exe) from https://github.com/bwapi/bwapi/releases/tag/v4.2.0, the solution is to register/log into https://my.visualstudio.com/ (so you need to already have an account, or you need to register) then click "Downloads" from the menu then type "Visual Studio Community 2017 (version 15.0)" in the search field (not version 15.7 or higher!) and download it (don't try to install it yet) then uninstall Visual Studio Community 2017 then install 15.0.  Note: 15.0 doesn't seem to be available at https://visualstudio.microsoft.com/downloads/ or https://visualstudio.microsoft.com/vs/older-downloads/ - it appears you need to log into https://my.visualstudio.com/ to get it.  You might also want to consider following the instructions at https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio so that you can install 15.0 again in future (on other machines in future, or when this problem inevitably happens again).

Long story:
In July 2017 I installed Visual Studio Community 2017 version 15.2.6 (i.e. Build version 15.0.26430.16 - FYI the version-to-BuildVersion mapping is documented at https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates). Yesterday I wanted to install an additional component but the it wouldn't let me install the component unless I upgraded Visual Studio Community 2017 to the latest version (15.7.4). There were no warnings about why I might not want to upgrade, so I upgraded, and immediately regretted it because of the **"LINK : fatal error C1047: The object or library file 'BWAPI.lib' was created with an older compiler than other objects; rebuild old objects and libraries"** problem.  I still had a copy of the old bootstrap installer lying around (VS_Community.exe) and tried fruitlessly for hours trying to downgrade to 15.2.6 or create an offline installer of 15.2.6 using the VS_Community.exe file (e.g. https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017 and
https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio and
https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network and scouring the forums), but nothing worked - it always got the latest version rather than 15.2.6.  As a last resort, I tried to find a way to install 15.0.x or 15.1.x and found the solution I described in the "Short story" works.  I cleaned my solution and rebuilt (linking to the lib files in BWAPI_420.old.7z), and it rebuilt fine with no warnings/errors, and the Release build of my bot runs fine on the unaltered VM that I was using before I had any of these problems.

It is confusing - the version number naming convention Microsoft is using is confusing and is independent to the Build version number naming convention they are using - the 15.0 version currently available at https://my.visualstudio.com/ appears to currently install version 15.0.14 (i.e. Build version 15.0.26228.37) which was released more recently than 15.2.6 (i.e. Build version 15.0.26430.16).  To me, it looks like because of the compatibility problem between pre-15.3 and post-15.3 versions, Microsoft are now maintaining two branches - one for the latest (master) branch and one to represent a pre-15.3 branch that they are naming version "15.0.x".

Yesterday, I issued a support request to Microsoft (no response yet), but that was before I found the solution.

I suggest @heinermann considers updating the Release Note at https://github.com/bwapi/bwapi/releases/tag/v4.2.0 to mention that an alternative solution is to register/log into https://my.visualstudio.com/ (so you need to already have an account, or you need to register) then click "Downloads" from the menu then type "Visual Studio Community 2017 (version 15.0)" in the search field (not version 15.7 or higher!) and download it (don't try to install it yet) then uninstall Visual Studio Community 2017 then install 15.0.

**Comment by ChobitsTheZero** [comment]
I am also running into this issue, the new release aint doing it either. Does anyone have a fix/workaround for the problem. I have already done some looking around for answers throughout different issues but haven't gotten anything to work yet.

**Comment by heinermann** [comment]
Hey guys, as of BWAPI 4.4, BWAPILIB is just included with the AI projects. Try that out. If there are still issues, feel free to re-open.
