### ISSUE TITLE
Broodwar->canMake return true, but morph fail

### ISSUE THREAD

**Issue by sijiaxu** [bwapi/bwapi#784]
recently I have noticed on my opening building items that, there is a small chance about 10% that morph overlord fail.(maybe morph other items also has this problems)
I log some detail information and found that when morph fail, both the morph and Broodwar->canMake function return true. 
but there is a warning at the game screen,"not enough minerals" to indicate morph fail.
I also log the Broodwar->self()->minerals(), and it shows the current mineral amount meet.

Does anyone has idea about this problems?
I set local speed to 0, does it related to this?

Thanks

**Comment by sijiaxu** [comment]
my bwapi version is 4.1.2

**Comment by dgant** [comment]
That could be related to latency; if the minerals were available at the time you checked, but not several frames later at the time the command executed (perhaps because you spent them elsewhere).

**Comment by sijiaxu** [comment]
@dgant  Thanks! 😄
 
if this is caused by latency, how can I resolve it?
 does bwapi has functions to prevent this or it rely on bot's implement to double check the morph status?

**Comment by dgant** [comment]
BWAPI can tell you what the latency settings are. BWAPI's latency compensation can hide some of the effects of latency. But otherwise it's up to you. Take a look at http://www.teamliquid.net/blogs/519872-towards-a-good-sc-bot-p56-latency for more details.

A lot of bots use a resource reservation system. They plan out what they want to build, in what order. If they want to spend resources on something, they only do so if those resources aren't allocated to something else with higher priority.

For example:
* I want to build a Hydralisk (reserve 75 minerals, 25 gas, 2 supply, and 1 larva)
* Then I want to build an Overlord (reserve 50 minerals and 1 larva)

Step 1:  I currently have 150 minerals, 20 gas, 2 supply, and 2 larva. I reserve all of that for the Hydralisk, which I can't build yet since I only have 20 gas. That only leaves 75 minerals for the Overlord, so I can't build that either

Step 2:  I currently have 170 minerals, 25 gas, 2 supply, and 2 larva. I can now build the hydralisk. I order a larva to morph into a Hydralisk. I don't release the reservation until I can see that the Hydralisk has started morphing (because that's how I know the money was spent. That leaves me with only 95 minerals for the Overlord, so I can't morph it yet.

Step 3: I currently have 105 minerals, 0 gas, 0 supply, and 1 larva. Also, the larva I ordered to morph into a Hydralisk is now an Egg that's training a Hydralisk. Now I can be sure that the Hydralisk resources were spent, so I release the Hydralisk resource reservation. And I have enough left to morph the Overlord, so now I morph that.

**Comment by sijiaxu** [comment]
@dgant  great post! really thanks 😄 

the latency explain many problems, but I still can not figure out why on my opening stage, the morph command fail and raise the "not enough minerals" warning.
I notice that when I play LAN games, the morph command fail phenomenon can even occur in my first three building of drone. the Broodwar->canMake  return true and the resource meet
from my understanding, the latency may not influence here because at opening stage action is executed sequentially in queue. there is no other stuff to consume resource in the same time.

**Comment by sijiaxu** [comment]
update.
after adding resource reservation system, all production become stable.
Thanks @dgant
