### ISSUE TITLE
When will be released BWAPI 5.0?

### ISSUE THREAD

**Issue by mathto** [bwapi/bwapi#816]
Hi everyone,

I am Charlie Bae, the Leader of SAIDA bot.

Many Korean Starcraft users have been inquiring about when SAIDA bot will run on the remastered version.

If you are know with the progress of the BWAPI 5.0 project, please share it.

I would like to help if there is any part to contribute to the development of the BWAPI 5.0 project.

Sincerely,
Charlie Bae

**Comment by heinermann** [comment]
Hi welcome. I made a document detailing what I planned for BWAPI5 [here](https://docs.google.com/document/d/11cq9ACPX4lpJcubc-Xq1ozvfXwrrE8Z07R8y1LjACss/edit?usp=drivesdk).

There's a bwapi5 branch but we haven't been very diligent in working on it.

Blizzard has done some work as well and the current plan last time I was in touch was to use a modified version of the SC2 Protobuf.

Ultimately Blizzard's part and bwapi5 can be developed separately, so I don't think anything is blocking either party but we'll have a better success if we can finish bwapi5.

You're free to make pull requests, though right now I don't think it compiles yet since N00by was doing some refactoring. The Protobuf stuff might be a little different as well.
