### ISSUE TITLE
No lib folder in BWAPI version 4.4.0

### ISSUE THREAD

**Issue by TheGeekiestOne** [bwapi/bwapi#827]
No lib folder in BWAPI version 4.4.0

Visual Studio 2017 10.0.17763.0, Windows 10

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'BWAPI.lib'	CommandCenter	C:\SCBW\masterBot\vs\LINK	1	
`

**Comment by N00byEdge** [comment]
Add the BWAPILib project as a dependency to your bot and BWAPILib.lib will be built by Visual studio when needed.

**Comment by TheGeekiestOne** [comment]
How would I do that, would it be under Linker > General > Additional Library Directories? 

And Do I still require Visual Studio 2013?

**Comment by N00byEdge** [comment]
No, VS 2017 is required.

You're supposed to add BWAPILIB (and its dependency, SVNRevGen) projects to your bot solution from BWAPI. Then add it as a dependency:
![image](https://user-images.githubusercontent.com/2322546/56589682-060e6180-65e6-11e9-906a-62f3508b9f23.png)
You don't need any library directories except the output directory of your bot.

Right click BWAPILIB and choose build to see that the files are being built, and where:
![image](https://user-images.githubusercontent.com/2322546/56589847-51287480-65e6-11e9-9cb4-761106396500.png)

**Comment by BryanSWeber** [comment]
This might be a sticking point for a few others, since @N00byEdge's picture is slightly truncated,  You have to declare BWAPILIB as a *dependency of the solution* and as a *reference of your specific bot project* using the same right-click menu. My project looks something like this:

![image](https://user-images.githubusercontent.com/29549711/65817124-7e9acf00-e1d1-11e9-96fb-0fa6072c6543.png)
