### ISSUE TITLE
Add upgrade level fields to units

### ISSUE THREAD

**Issue by N00byEdge** [bwapi/bwapi#840]
Units which have been mind controlled can have a higher upgrade level than its owner upgrade level. There is no interface for getting the upgrade level (shield, armor, weapons) of a specific unit at this moment.

**Comment by chriscoxe** [comment]
I agree that it would be convenient if this info was more readily accessible from the unit rather than just from the player.  Are you sure that the following statement is correct though?
> Units which have been mind controlled can have a higher upgrade level than its owner upgrade level.

https://starcraft.fandom.com/wiki/Mind_control says:
> mind controlling a unit that has researched upgrades or special abilities will transfer them to the dark archon's player.

That was my understanding, and it means that after the mind control is completed, the unit could not have a higher upgrade level than the player's new upgrade level.  However, I don't know whether it also means that if a player that has a high upgrade level mind controls an unit it doesn't own which has a lower upgrade level than the player, whether the unit's upgrade level would automatically be increased to match the player's upgrade level.

**Comment by N00byEdge** [comment]
Hm, looks like you're not getting the upgrade levels for attack/armor/shields. Only abilities, research, movement speed etc. Here is the code related to this: https://github.com/OpenBW/openbw/blob/master/bwgame.h#L3223

**Comment by NiteKat** [comment]
I did some in game testing and can confirm, at least when you MC another Protoss unit, weapon/armor/shield upgrade levels get set to the player's current level, but abilities, research etc. transfer over.

**Comment by heinermann** [comment]
You don't get repeatable upgrades, you do get singular upgrades and abilities. Those are not unit-specific and get transferred to all of your own units.

**Comment by N00byEdge** [comment]
Oh okay, we should just use the owning players upgrade levels then.
