### ISSUE TITLE
CancelConstruction/CancelMorph changes type before Unit changes type

### ISSUE THREAD

**Issue by Cmccrave** [bwapi/bwapi#853]
From some discussion I had (with myself mostly), I found that manually cancelling a morphing building (with input enabled) will act correctly but not when using the BWAPI CancelConstruction or CancelMorph. With some deep diving I found that the UnitType of a building is changing 1 frame before the UnitType should be changing, resulting in a Drone morphing from a Drone.

Ignore the console output, as it's not as relevant. But you can see that the current UnitType is a Zerg_Spawning_Pool. I made some test code that cancels it at 200hp.

![image](https://user-images.githubusercontent.com/25108498/80033702-2f90f000-84bb-11ea-9d7d-d003c48b7d76.png)

2 frames later, it is a Zerg_Drone while still a Zerg_Spawning_Pool.

![image](https://user-images.githubusercontent.com/25108498/80033741-3ddf0c00-84bb-11ea-9bdb-32eb46060dbc.png)

**Comment by N00byEdge** [comment]
The type of the spawning pool should change to a drone through latcom on the frame you commanded the cancellation (https://github.com/bwapi/bwapi/blob/e4a29d73e6021037901da57ceb06e37248760240/bwapi/include/BWAPI/Client/CommandTemp.h#L365). Are you using latcom? If so, I believe this is expected behavior.

**Comment by Cmccrave** [comment]
Probably not a bug, closing

**Comment by heinermann** [comment]
Try disabling latency compensation.
